name: Output Infrastructure

on:
  workflow_call:
    inputs:
      traffic:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo "${{ inputs.traffic }}"