name: Scale Infrastructure

environment: production

on:
  workflow_dispatch:

jobs:
  resize:
    uses: tarasom/reusable-workflows/.github/workflows/node-pool-scaling.yml@main
    secrets: inherit
    with:
      num_nodes: 2