name: Scale Infrastructure

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select the env
        options:
          - dev
          - prod
      traffic:
        type: choice
        description: Select the traffic mode
        options:
          - usual
          - high

jobs:
  resize:
    uses: tarasom/reusable-workflows/.github/workflows/node-pool-scaling.yml@main
    environment: dev
    secrets:
    with:
      num_nodes: 2