name: Scale Infrastructure

on:
  workflow_dispatch:

jobs:
  resize-usual-workload:
    name: Resize Usual Workload Node Pool
    uses: tarasom/reusable-workflows/.github/workflows/node-pool-scaling.yml@main
    with:
      env: production
      node_pool: np-dev-main
      num_nodes: 1

  resize-heavy-workload:
    name: Resize Heavy Workload Node Pool
    uses: tarasom/reusable-workflows/.github/workflows/node-pool-scaling.yml@main
    needs: resize-usual-workload
    with:
      env: production
      node_pool: np-dev-spot
      num_nodes: 0
